// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: testdrive.proto

package testdrive

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//请求
type TestDriveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//userid
	Userid int32 `protobuf:"varint,1,opt,name=Userid,proto3" json:"Userid,omitempty"`
	//品牌
	Carband string `protobuf:"bytes,2,opt,name=Carband,proto3" json:"Carband,omitempty"`
	//车系
	CarSeries string `protobuf:"bytes,3,opt,name=CarSeries,proto3" json:"CarSeries,omitempty"`
	//城市
	City string `protobuf:"bytes,4,opt,name=City,proto3" json:"City,omitempty"`
	//姓名
	Username string `protobuf:"bytes,5,opt,name=Username,proto3" json:"Username,omitempty"`
	//手机号
	PhoneNumber string `protobuf:"bytes,6,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
}

func (x *TestDriveRequest) Reset() {
	*x = TestDriveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdrive_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestDriveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestDriveRequest) ProtoMessage() {}

func (x *TestDriveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testdrive_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestDriveRequest.ProtoReflect.Descriptor instead.
func (*TestDriveRequest) Descriptor() ([]byte, []int) {
	return file_testdrive_proto_rawDescGZIP(), []int{0}
}

func (x *TestDriveRequest) GetUserid() int32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *TestDriveRequest) GetCarband() string {
	if x != nil {
		return x.Carband
	}
	return ""
}

func (x *TestDriveRequest) GetCarSeries() string {
	if x != nil {
		return x.CarSeries
	}
	return ""
}

func (x *TestDriveRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *TestDriveRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TestDriveRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type MyTestDriveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//userid
	Userid int32 `protobuf:"varint,1,opt,name=Userid,proto3" json:"Userid,omitempty"`
}

func (x *MyTestDriveRequest) Reset() {
	*x = MyTestDriveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdrive_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyTestDriveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyTestDriveRequest) ProtoMessage() {}

func (x *MyTestDriveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testdrive_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyTestDriveRequest.ProtoReflect.Descriptor instead.
func (*MyTestDriveRequest) Descriptor() ([]byte, []int) {
	return file_testdrive_proto_rawDescGZIP(), []int{1}
}

func (x *MyTestDriveRequest) GetUserid() int32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

//返回
type TestDriveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//品牌
	Carband string `protobuf:"bytes,2,opt,name=Carband,proto3" json:"Carband,omitempty"`
	//车系
	CarSeries string `protobuf:"bytes,3,opt,name=CarSeries,proto3" json:"CarSeries,omitempty"`
	//城市
	City string `protobuf:"bytes,4,opt,name=City,proto3" json:"City,omitempty"`
	//status
	Status string `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *TestDriveResponse) Reset() {
	*x = TestDriveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdrive_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestDriveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestDriveResponse) ProtoMessage() {}

func (x *TestDriveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testdrive_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestDriveResponse.ProtoReflect.Descriptor instead.
func (*TestDriveResponse) Descriptor() ([]byte, []int) {
	return file_testdrive_proto_rawDescGZIP(), []int{2}
}

func (x *TestDriveResponse) GetCarband() string {
	if x != nil {
		return x.Carband
	}
	return ""
}

func (x *TestDriveResponse) GetCarSeries() string {
	if x != nil {
		return x.CarSeries
	}
	return ""
}

func (x *TestDriveResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *TestDriveResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_testdrive_proto protoreflect.FileDescriptor

var file_testdrive_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x72, 0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0xb4, 0x01, 0x0a, 0x10, 0x54, 0x65, 0x73,
	0x74, 0x44, 0x72, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x61, 0x72, 0x62, 0x61, 0x6e, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x61, 0x72, 0x62, 0x61, 0x6e, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x43, 0x61, 0x72, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x69, 0x74,
	0x79, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22,
	0x2c, 0x0a, 0x12, 0x4d, 0x79, 0x54, 0x65, 0x73, 0x74, 0x44, 0x72, 0x69, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0x77, 0x0a,
	0x11, 0x54, 0x65, 0x73, 0x74, 0x44, 0x72, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x61, 0x72, 0x62, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x61, 0x72, 0x62, 0x61, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x43, 0x61, 0x72, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x43, 0x61, 0x72, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x69,
	0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x9b, 0x01, 0x0a, 0x0f, 0x54, 0x65, 0x73, 0x74, 0x44,
	0x72, 0x69, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x09, 0x54, 0x65,
	0x73, 0x74, 0x44, 0x72, 0x69, 0x76, 0x65, 0x12, 0x17, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x54, 0x65, 0x73, 0x74, 0x44, 0x72, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x44, 0x72, 0x69,
	0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0f, 0x46, 0x69,
	0x6e, 0x64, 0x4d, 0x79, 0x54, 0x65, 0x73, 0x74, 0x44, 0x72, 0x69, 0x76, 0x65, 0x12, 0x19, 0x2e,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x4d, 0x79, 0x54, 0x65, 0x73, 0x74, 0x44, 0x72, 0x69, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x54, 0x65, 0x73, 0x74, 0x44, 0x72, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x30, 0x01, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x43, 0x61, 0x72, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x72, 0x69, 0x76, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testdrive_proto_rawDescOnce sync.Once
	file_testdrive_proto_rawDescData = file_testdrive_proto_rawDesc
)

func file_testdrive_proto_rawDescGZIP() []byte {
	file_testdrive_proto_rawDescOnce.Do(func() {
		file_testdrive_proto_rawDescData = protoimpl.X.CompressGZIP(file_testdrive_proto_rawDescData)
	})
	return file_testdrive_proto_rawDescData
}

var file_testdrive_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_testdrive_proto_goTypes = []interface{}{
	(*TestDriveRequest)(nil),   // 0: score.TestDriveRequest
	(*MyTestDriveRequest)(nil), // 1: score.MyTestDriveRequest
	(*TestDriveResponse)(nil),  // 2: score.TestDriveResponse
}
var file_testdrive_proto_depIdxs = []int32{
	0, // 0: score.TestDriveServer.TestDrive:input_type -> score.TestDriveRequest
	1, // 1: score.TestDriveServer.FindMyTestDrive:input_type -> score.MyTestDriveRequest
	2, // 2: score.TestDriveServer.TestDrive:output_type -> score.TestDriveResponse
	2, // 3: score.TestDriveServer.FindMyTestDrive:output_type -> score.TestDriveResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testdrive_proto_init() }
func file_testdrive_proto_init() {
	if File_testdrive_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testdrive_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestDriveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdrive_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyTestDriveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdrive_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestDriveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testdrive_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testdrive_proto_goTypes,
		DependencyIndexes: file_testdrive_proto_depIdxs,
		MessageInfos:      file_testdrive_proto_msgTypes,
	}.Build()
	File_testdrive_proto = out.File
	file_testdrive_proto_rawDesc = nil
	file_testdrive_proto_goTypes = nil
	file_testdrive_proto_depIdxs = nil
}
