// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package score

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScoreServiceClient is the client API for ScoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScoreServiceClient interface {
	//打分
	MakeScore(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
	//修改评分
	ModifyScore(ctx context.Context, in *ScoreResponse, opts ...grpc.CallOption) (*ScoreResponse, error)
	//查看评分
	FindMYScore(ctx context.Context, in *MyScoresRequest, opts ...grpc.CallOption) (ScoreService_FindMYScoreClient, error)
}

type scoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScoreServiceClient(cc grpc.ClientConnInterface) ScoreServiceClient {
	return &scoreServiceClient{cc}
}

func (c *scoreServiceClient) MakeScore(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	out := new(ScoreResponse)
	err := c.cc.Invoke(ctx, "/score.ScoreService/MakeScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoreServiceClient) ModifyScore(ctx context.Context, in *ScoreResponse, opts ...grpc.CallOption) (*ScoreResponse, error) {
	out := new(ScoreResponse)
	err := c.cc.Invoke(ctx, "/score.ScoreService/ModifyScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoreServiceClient) FindMYScore(ctx context.Context, in *MyScoresRequest, opts ...grpc.CallOption) (ScoreService_FindMYScoreClient, error) {
	stream, err := c.cc.NewStream(ctx, &ScoreService_ServiceDesc.Streams[0], "/score.ScoreService/FindMYScore", opts...)
	if err != nil {
		return nil, err
	}
	x := &scoreServiceFindMYScoreClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ScoreService_FindMYScoreClient interface {
	Recv() (*ScoreResponse, error)
	grpc.ClientStream
}

type scoreServiceFindMYScoreClient struct {
	grpc.ClientStream
}

func (x *scoreServiceFindMYScoreClient) Recv() (*ScoreResponse, error) {
	m := new(ScoreResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ScoreServiceServer is the server API for ScoreService service.
// All implementations must embed UnimplementedScoreServiceServer
// for forward compatibility
type ScoreServiceServer interface {
	//打分
	MakeScore(context.Context, *ScoreRequest) (*ScoreResponse, error)
	//修改评分
	ModifyScore(context.Context, *ScoreResponse) (*ScoreResponse, error)
	//查看评分
	FindMYScore(*MyScoresRequest, ScoreService_FindMYScoreServer) error
	mustEmbedUnimplementedScoreServiceServer()
}

// UnimplementedScoreServiceServer must be embedded to have forward compatible implementations.
type UnimplementedScoreServiceServer struct {
}

func (UnimplementedScoreServiceServer) MakeScore(context.Context, *ScoreRequest) (*ScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeScore not implemented")
}
func (UnimplementedScoreServiceServer) ModifyScore(context.Context, *ScoreResponse) (*ScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyScore not implemented")
}
func (UnimplementedScoreServiceServer) FindMYScore(*MyScoresRequest, ScoreService_FindMYScoreServer) error {
	return status.Errorf(codes.Unimplemented, "method FindMYScore not implemented")
}
func (UnimplementedScoreServiceServer) mustEmbedUnimplementedScoreServiceServer() {}

// UnsafeScoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScoreServiceServer will
// result in compilation errors.
type UnsafeScoreServiceServer interface {
	mustEmbedUnimplementedScoreServiceServer()
}

func RegisterScoreServiceServer(s grpc.ServiceRegistrar, srv ScoreServiceServer) {
	s.RegisterService(&ScoreService_ServiceDesc, srv)
}

func _ScoreService_MakeScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoreServiceServer).MakeScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/score.ScoreService/MakeScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoreServiceServer).MakeScore(ctx, req.(*ScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoreService_ModifyScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoreServiceServer).ModifyScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/score.ScoreService/ModifyScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoreServiceServer).ModifyScore(ctx, req.(*ScoreResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoreService_FindMYScore_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MyScoresRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ScoreServiceServer).FindMYScore(m, &scoreServiceFindMYScoreServer{stream})
}

type ScoreService_FindMYScoreServer interface {
	Send(*ScoreResponse) error
	grpc.ServerStream
}

type scoreServiceFindMYScoreServer struct {
	grpc.ServerStream
}

func (x *scoreServiceFindMYScoreServer) Send(m *ScoreResponse) error {
	return x.ServerStream.SendMsg(m)
}

// ScoreService_ServiceDesc is the grpc.ServiceDesc for ScoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "score.ScoreService",
	HandlerType: (*ScoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeScore",
			Handler:    _ScoreService_MakeScore_Handler,
		},
		{
			MethodName: "ModifyScore",
			Handler:    _ScoreService_ModifyScore_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FindMYScore",
			Handler:       _ScoreService_FindMYScore_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "score.proto",
}
